build:
  environment:
    php: 8.0.0

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    tests-and-coverage:
      tests:
        override:
          - phpcs-run ./src

checks:
  php:
    code_rating: true
    duplication: true

filter:
  excluded_paths:
    - test/*
    - vendor/*